-- Add pinned_order column to support ordering of pinned items
ALTER TABLE sports ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE news ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
ALTER TABLE cheer_wall ADD COLUMN IF NOT EXISTS pinned_order INTEGER DEFAULT 0;
